# Набор тестов для эндпоинтов которые можно запустить
# в VSCode с помощью плагина  REST Client
# Найти можно по идентификатору: humao.rest-client
# Tunder Client не позволяет свободно импортировать-экспортировать записи,
# поэтому перешел на этот плагин. Он тоже хорош :-)

# Создаем продавца
POST http://localhost:8000/api/v1/seller/ HTTP/1.1
content-type: application/json

{
    "first_name": "Kirill",
    "last_name": "Shevchenko",
    "email": "ro2b3223@gmail.com",
    "password": "K102!3f823"
}

###

# Создаем токен
POST http://localhost:8000/api/v1/token/ HTTP/1.1
content-type: application/json

{
    "email": "ro2b3223@gmail.com",
    "password": "K102!3f823"
}

###

# Получаем список продавцов
GET http://localhost:8000/api/v1/seller/ HTTP/1.1

###

# Получаем одного продавца по его ИД
# ! Важно ! Добавить в заголовок запроса токен после его получения
GET http://localhost:8000/api/v1/seller/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJybzJiMzIyM0BnbWFpbC5jb20iLCJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3MDg2MTIyNjF9.7q4sSAQT4LP5BAOtyfiQrxibU0e1MEpAHBjGx0539wU

###

# Обновляем поля в данных о продавце
PUT http://localhost:8000/api/v1/seller/1 HTTP/1.1
content-type: application/json

{
    "id": 0,
    "first_name": "Kirill",
    "last_name": "Shevchenko",
    "email": "kik1203_2@gmail.com",
    "password": "K10f832f3!"
}

###

# Удаляем продавца
DELETE http://localhost:8000/api/v1/seller/1 HTTP/1.1
content-type: application/json

###

# Создаем книгу
# ! Важно ! Добавить в заголовок запроса токен после его получения
POST http://localhost:8000/api/v1/books/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJybzJiMzIyM0BnbWFpbC5jb20iLCJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3MDg2MTIyNjF9.7q4sSAQT4LP5BAOtyfiQrxibU0e1MEpAHBjGx0539wU

{
    "title": "Wrong Code",
    "author": "Robert Martin",
    "pages": 464,
    "year": 2008,
    "seller_id": 1
}

###

# Получаем список книг
GET http://localhost:8000/api/v1/books/ HTTP/1.1

###

# Получаем одну книгу по ее ИД
GET http://localhost:8000/api/v1/books/1 HTTP/1.1

###

# Обновляем поля в данных о книге
# ! Важно ! Добавить в заголовок запроса токен после его получения
PUT http://localhost:8000/api/v1/books/1 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJybzJiMzIyM0BnbWFpbC5jb20iLCJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3MDg2MTIyNjF9.7q4sSAQT4LP5BAOtyfiQrxibU0e1MEpAHBjGx0539wU

{
    "title": "Clean Code",
    "author": "Robert Martin",
    "count_pages": 455,
    "year": 2002,
    "id": 0,
    "seller_id": 0
}

###

# Удаляем книгу
DELETE http://localhost:8000/api/v1/books/1 HTTP/1.1
content-type: application/json

###